server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:~/test'
    username: 'sa'
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6378
      password: medicall11
      timeout: 2000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6f0b3452ff270352a9370ead40f1730c
            client-secret: urn2CQCUtbBe9SApEYxOJGwQ9nPpIsX6
            scope:
              - profile_nickname
              - profile_image
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  access:
    secret: 8ed3d8a1f74cf6ba0815e9c58e87d708973907f5218a052ac57e5b3cb13d074b
    expires-in: 7200
  refresh:
    secret: d483f13b53ffb4b4ca45156ea0ffdf32e4cabd4a901556d69d7355ba1f548d52
    expires-in: 604800
  allowance:
    secret: e20b675a52da5aa6d3d181dc69614e38d13ed80fd88c162cdd93047c566cd805
    expires-in: 900

cookie:
  expiration: 3600
  domain: localhost
  max-age: 300
  access-name: ac_t
  refresh-name: rf_t

frontend:
  auth-redirect-url: http://localhost:3000/loading
  base-url: http://localhost:3000
  allowance-redirect-url: http://localhost:3000/login/term

backend:
  base-url: http://localhost:8080