server:
  port: 80

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:~/test'
    username: 'sa'
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6f0b3452ff270352a9370ead40f1730c
            client-secret: urn2CQCUtbBe9SApEYxOJGwQ9nPpIsX6
            scope:
              - profile_nickname
              - profile_image
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/kakao/oauth
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
